

variables:
  Environnement_STAGING: "Staging"
  Environnement_PROD: "Prod"
  Ansible_Image_name: "ghcr.io/ansible-community/community-ee-minimal" 
  Ansible_Image_Tag: "2.20.6-1"
  ANSIBLE_COLLECTIONS_PATH: "$CI_PROJECT_DIR/.ansible/collections"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - Check
  - Simulate
  - Execute

default:
  interruptible: false
  cache:
    key:
      files:
        - requirements.yml
    paths:
      - .ansible/collections
      - .cache/pip
    

# 
Syntax_check:
  stage: Check
  image: "$Ansible_Image_name:$Ansible_Image_Tag"

  before_script:
  
    - pip install ansible-lint==26.6.0
    - ansible-galaxy collection install -r requirements.yml -p "$ANSIBLE_COLLECTIONS_PATH"
    
  # syntax checking 
  script:

    - ansible-lint .
    - ansible-playbook -i inventories/stage/hosts.yml playbooks/autoflow_manage.yml --syntax-check
  
  cache:
    policy: pull-push

Simu_simulate:
  stage: Simulate
  environment: "$Environnement_STAGING"
  image: "$Ansible_Image_name:$Ansible_Image_Tag"
  needs: ["Syntax_check"]
  

  # Action to execute before official script
  before_script:

    - ansible-galaxy collection install -r requirements.yml -p "$ANSIBLE_COLLECTIONS_PATH"
    - chmod 400 "$SSH_PRIVATE_KEY"
    # test of connectivity with ping module
    - ansible workers -i inventories/stage/hosts.yml -m ping --private-key "$SSH_PRIVATE_KEY"
       
  
  script:

    # playbook execution in silence mode (--check)
    - ansible-playbook -i inventories/stage/hosts.yml playbooks/autoflow_manage.yml --tags "install_packages" --limit "autoflows" --check --private-key "$SSH_PRIVATE_KEY"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  cache:
    policy: pull




# Execution of pipeline in real scenario
Pipeline_Execution:

  image: "$Ansible_Image_name:$Ansible_Image_Tag"
  stage: Execute
  environment: "$Environnement_PROD"
  needs: ["Simu_simulate"]
    
  before_script:

    - ansible-galaxy collection install -r requirements.yml -p "$ANSIBLE_COLLECTIONS_PATH"

    - chmod 400 "$SSH_PRIVATE_KEY"

  script:

    - ansible-playbook -i inventories/prod/hosts.yml playbooks/autoflow_manage.yml --tags "install_packages" --limit "autoflows" --private-key "$SSH_PRIVATE_KEY"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
  cache:
    policy: pull