all:

  children:

    autoflows:

      hosts:

        autoflow1:

          ansible_host: 192.168.9.180  # penser à la notion du DNS 
          #ansible_user: worker
    

    workers:

      hosts:

        workers1:

          ansible_host: 192.168.9.182
          #ansible_user: worker4 # Temporary user; comment out or remove after creating the dedicated Ansible user


    local:

      hosts:

        localhost:

          ansible_connection: local
          