---
# vars file for ssh_hardening

system_owner: "root"
system_group: "root"
ssh_sshd_binary: "/usr/sbin/sshd"
ssh_main_config_file: "/etc/ssh/sshd_config"
path_target_configuration: "/etc/ssh/sshd_config.d"
ssh_config_validation: "/bin/sh -c 'cat %s {{ ssh_main_config_file }} | {{ssh_sshd_binary}} -t -f /dev/stdin'"
ssh_file_mode: "0600"
ssh_directory_mode: "0755"

