all:

  children:

    autoflows:

      hosts:

        autoflow1:

          ansible_host: 192.168.9.  ## Pensez au DNS au bon moment
          ansible_user: "{{ host_username }}"
          

    local:

      hosts:

        localhost:

          ansible_connection: local