---
# tasks file for ssh_hardening

- name: check if ssh is absent and install it 
  ansible.builtin.apt:
    name: openssh-server
    state: present


- name: Ensure that ssh service is running and enabled
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: yes

- name: "Ensure that {{ path_target_configuration }} exists"
  ansible.builtin.file:
    path: "{{ path_target_configuration }}"
    state: directory
    owner: "{{ system_owner }}"
    group: "{{ system_group }}"
    mode: "{{ ssh_directory_mode }}"


- name: ssh hardening configuration path_file and rules
  ansible.builtin.template:
    src: ssh_hardening.conf.j2
    dest: "{{ path_target_configuration }}/{{ file_name }}"
    owner: "{{ system_owner }}"
    group: "{{ system_group }}"
    mode: "{{ ssh_file_mode  }}"
    validate: "{{ ssh_config_validation }}"
  notify: restart ssh 