---
- name: execute tasks on autoflows customer
  hosts: autoflows
  gather_facts: true
  become: true

  roles:

    - role: bootstrap_user
      tags: user
    - role: ssh_hardening
      tags: ssh
    - role: packages
      tags: install_packages